---
- name: Stop Telegraf
  hosts: all
  gather_facts: false
  vars:
    wd: "{{ wd_base }}/{{ inventory_hostname }}"
    telegraf_pidfile: "{{ wd }}/telegraf-{{ inventory_hostname }}.pid"
  tasks:
    - name: Read Telegraf PID (if present)
      shell: "cat {{ telegraf_pidfile }}"
      register: pid_read
      changed_when: false
      failed_when: false

    - name: Set PID (trim) if pidfile exists
      set_fact:
        telegraf_pid: "{{ pid_read.stdout | trim }}"
      when: pid_read.rc == 0 and (pid_read.stdout | trim) != ""

    - name: Skip stop if not running
      debug:
        msg: "Telegraf not running; skipping."
      when: telegraf_pid is not defined

    - name: Graceful stop (SIGTERM)
      shell: "kill {{ telegraf_pid }}"
      when: telegraf_pid is defined
      failed_when: false

    - name: Wait for Telegraf to stop (15s)
      wait_for:
        path: "/proc/{{ telegraf_pid }}/status"
        state: absent
        timeout: 15
      when: telegraf_pid is defined
      failed_when: false

    - name: Remove pidfile
      file:
        path: "{{ telegraf_pidfile }}"
        state: absent
      when: telegraf_pid is defined